apiVersion: apps/v1
kind: Deployment
metadata:
  name: pangolin-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pangolin-operator
  template:
    metadata:
      labels:
        name: pangolin-operator
    spec:
      serviceAccountName: pangolin-operator
      containers:
        - name: pangolin-operator
          # Replace this with the built image name
          image: docker.netzlink.com/operators/pangolin-operator@sha256:770abf4e0833e0a5eba009c0da26207558429c50d85dd0cc8780a9e0b0fd0c29
          command:
          - pangolin-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pangolin-operator"
