apiVersion: apps/v1
kind: Deployment
metadata:
  name: pangolin-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pangolin-operator
  template:
    metadata:
      labels:
        name: pangolin-operator
    spec:
      serviceAccountName: pangolin-operator
      containers:
        - name: pangolin-operator
          # Replace this with the built image name
          image: docker.netzlink.com/operators/pangolin-operator@sha256:773ac92f8a9d860b532618156de193d7d89dde9cd39b7a7895e930a558e3b53e
          command:
          - pangolin-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pangolin-operator"
