apiVersion: pangolin.netzlink.com/v1alpha1
kind: BackupJob
metadata:
  name: nli-ipam
spec:
  schedule: "0 */12 * * *"
  extras: "-q"
  type:
    mariadb: true
  databaseConfig:
    endpoint: mariadb-0.mariadb.netzwerk.svc.cluster.local # maybe port
    database: phpipam
    user: root
    passwordSecret: ipam-database-bakup-secret
  s3Config:
    endpoint: http://rook-ceph-rgw-ocp4-object-store.rook-ceph.svc.cluster.local
    bucket:   pangolin-backups
    secret:   ipam-database-bakup-secret